#!/usr/bin/env bash
# Bakes the contents of embedded/*.pony into a Pony source file that
# exposes them as String val constants via an `EmbeddedResources`
# primitive. The CLI calls EmbeddedResources.all() at emit time and
# writes each (target_path, content) tuple to disk.
#
# Usage:
#   tools/bake_embedded.sh > emitter/embedded_resources.pony
#
# Inputs (hardcoded): embedded/gobject_runtime/handle.pony
#                     embedded/gtk/runtime.pony

set -euo pipefail

cd "$(dirname "$0")/.."

emit_file() {
  local pony_fn_name="$1"
  local src_path="$2"

  echo "  fun $pony_fn_name(): String val =>"
  # Each source line becomes `"<escaped line>\n" +`; the last has no `+`.
  # We escape backslash first, then double-quote.
  local lines
  lines=$(awk '
    {
      gsub(/\\/, "\\\\")
      gsub(/"/, "\\\"")
      print
    }
  ' "$src_path")

  local n
  n=$(printf '%s\n' "$lines" | wc -l)
  local i=0
  while IFS= read -r line; do
    i=$((i + 1))
    if [ "$i" -lt "$n" ]; then
      printf '    "%s\\n" +\n' "$line"
    else
      printf '    "%s\\n"\n' "$line"
    fi
  done <<<"$lines"
  echo ""
}

cat <<'HEADER'
// Generated by tools/bake_embedded.sh — do not edit by hand.
//
// Embedded handwritten runtime support files. The CLI writes these
// out alongside generated bindings so the target directory is a
// complete buildable package tree.

primitive EmbeddedResources
  fun all(): Array[(String val, String val)] val =>
    """
    Returns (target-relative-path, content) tuples. The emitter
    iterates these and writes each one alongside generated files.
    """
    recover val
      [
        ("gobject_runtime/handle.pony", _gobject_runtime_handle())
        ("gtk/runtime.pony",            _gtk_runtime())
      ]
    end

HEADER

emit_file "_gobject_runtime_handle" "embedded/gobject_runtime/handle.pony"
emit_file "_gtk_runtime"            "embedded/gtk/runtime.pony"
